import React, { useMemo } from "react";
import { playerNameFromForm } from "../utils/playerDetails";
import { POSITION_OPTIONS } from "../utils/playerDetails";
import { normalizeHighlightThemeKey } from "../utils/highlightCardStyles";
import { normalizeTierKey } from "../utils/cardTemplate";

const THEME_PREVIEW_CLASS = {
  neon: "studio-live-preview--theme-neon",
  holographic: "studio-live-preview--theme-holo",
  chrome: "studio-live-preview--theme-chrome",
  retro: "studio-live-preview--theme-retro",
  gold_edition: "studio-live-preview--theme-gold",
  midnight: "studio-live-preview--theme-midnight",
  inferno: "studio-live-preview--theme-inferno",
  mvp: "studio-live-preview--theme-mvp",
  diamond: "studio-live-preview--theme-diamond",
  hall_of_fame: "studio-live-preview--theme-hof",
  halloween: "studio-live-preview--theme-halloween",
  christmas: "studio-live-preview--theme-christmas",
};

function positionLabel(code) {
  const match = POSITION_OPTIONS.find((o) => o.value === code);
  return match?.label || code || "";
}

export default function StudioLivePreview({
  firstName = "",
  lastName = "",
  displayName = "",
  position = "",
  jerseyNumber = "",
  teamName = "",
  tier = "",
  theme = "",
  photoUrl = "",
}) {
  const playerName = playerNameFromForm(firstName, lastName, displayName);
  const hasPlayerInfo = playerName.length >= 2;
  const tierKey = normalizeTierKey(tier || "rookie");
  const themeKey = normalizeHighlightThemeKey(theme);

  const tierClass =
    tierKey === "legends"
      ? "studio-live-preview__frame--legends"
      : tierKey === "allstar"
        ? "studio-live-preview__frame--allstar"
        : tierKey === "rookie" && tier
          ? "studio-live-preview__frame--rookie"
          : "";

  const themeClass = THEME_PREVIEW_CLASS[themeKey] || "";

  const posText = useMemo(() => positionLabel(position), [position]);

  return (
    <div className="studio-live-preview-wrap">
      <div className={`studio-live-preview__frame ${tierClass} ${themeClass}`}>
        {photoUrl ? (
          <>
            <img src={photoUrl} alt="" className="studio-live-preview__photo" />
            <div className="studio-live-preview__photo-gradient" aria-hidden />
          </>
        ) : null}
        {jerseyNumber.trim() ? (
          <span className="studio-live-preview__jersey">#{jerseyNumber.trim()}</span>
        ) : null}
        <div
          className={`studio-live-preview__info${
            hasPlayerInfo ? "" : " studio-live-preview__info--empty"
          }`}
        >
          {hasPlayerInfo ? (
            <>
              <p className="studio-live-preview__name">{playerName}</p>
              {posText ? <p className="studio-live-preview__position">{posText}</p> : null}
              {teamName.trim() ? <p className="studio-live-preview__team">{teamName.trim()}</p> : null}
            </>
          ) : (
            <>
              <p className="studio-live-preview__placeholder-title">Your Card</p>
              <p className="studio-live-preview__placeholder-sub">
                Start filling in your info to see it come to life
              </p>
            </>
          )}
        </div>
      </div>
      <p className="studio-live-preview__disclaimer">
        Live Preview — Final card generated by AI
      </p>
    </div>
  );
}
