"""Per-user card generation usage caps (beta cost protection)."""

from __future__ import annotations

import os
from datetime import datetime, timedelta, timezone

from sqlalchemy import and_, or_
from sqlalchemy.orm import Session

from models import Card


def get_generation_caps() -> tuple[int, int]:
    daily_cap = int(os.environ.get("DAILY_GENERATION_CAP", "50"))
    monthly_cap = int(os.environ.get("MONTHLY_GENERATION_CAP", "200"))
    return daily_cap, monthly_cap


def _period_start(period: str) -> datetime:
    now = datetime.now(timezone.utc)
    if period == "daily":
        return now.replace(hour=0, minute=0, second=0, microsecond=0)
    return now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)


def _daily_reset_at() -> datetime:
    now = datetime.now(timezone.utc)
    start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    return start + timedelta(days=1)


def _monthly_reset_at() -> datetime:
    now = datetime.now(timezone.utc)
    if now.month == 12:
        return now.replace(
            year=now.year + 1,
            month=1,
            day=1,
            hour=0,
            minute=0,
            second=0,
            microsecond=0,
        )
    return now.replace(
        month=now.month + 1,
        day=1,
        hour=0,
        minute=0,
        second=0,
        microsecond=0,
    )


def _user_generation_filter(user_id: int, start: datetime):
    return and_(
        or_(
            Card.creator_user_id == user_id,
            and_(Card.creator_user_id.is_(None), Card.owner_id == user_id),
        ),
        Card.created_at >= start,
        Card.status != "discarded",
    )


def _platform_generation_filter(start: datetime):
    return and_(Card.created_at >= start, Card.status != "discarded")


def get_user_generation_count(db: Session, user_id: int, period: str) -> int:
    """Count cards generated by user in period (daily or monthly)."""
    start = _period_start(period)
    return int(
        db.query(Card)
        .filter(_user_generation_filter(user_id, start))
        .count()
    )


def get_platform_generation_count(db: Session, period: str) -> int:
    start = _period_start(period)
    return int(db.query(Card).filter(_platform_generation_filter(start)).count())


def check_generation_cap(db: Session, user_id: int) -> tuple[bool, str | None]:
    """Returns (allowed, message)."""
    daily_count = get_user_generation_count(db, user_id, "daily")
    monthly_count = get_user_generation_count(db, user_id, "monthly")
    daily_cap, monthly_cap = get_generation_caps()

    if daily_count >= daily_cap:
        return False, (
            f"You have reached your daily limit of {daily_cap} card generations. "
            f"Your limit resets at midnight."
        )

    if monthly_count >= monthly_cap:
        return False, (
            f"You have reached your monthly limit of {monthly_cap} card generations. "
            f"Your limit resets on the 1st of next month."
        )

    return True, None


def generation_cap_hit_period(db: Session, user_id: int) -> str | None:
    daily_count = get_user_generation_count(db, user_id, "daily")
    monthly_count = get_user_generation_count(db, user_id, "monthly")
    daily_cap, monthly_cap = get_generation_caps()
    if daily_count >= daily_cap:
        return "daily"
    if monthly_count >= monthly_cap:
        return "monthly"
    return None


def generation_usage_payload(db: Session, user_id: int) -> dict:
    daily_count = get_user_generation_count(db, user_id, "daily")
    monthly_count = get_user_generation_count(db, user_id, "monthly")
    daily_cap, monthly_cap = get_generation_caps()
    daily_reset = _daily_reset_at()
    monthly_reset = _monthly_reset_at()
    return {
        "daily_count": daily_count,
        "daily_cap": daily_cap,
        "daily_remaining": max(0, daily_cap - daily_count),
        "daily_resets": daily_reset.isoformat().replace("+00:00", "Z"),
        "monthly_count": monthly_count,
        "monthly_cap": monthly_cap,
        "monthly_remaining": max(0, monthly_cap - monthly_count),
        "monthly_resets": monthly_reset.isoformat().replace("+00:00", "Z"),
        "cap_hit": generation_cap_hit_period(db, user_id),
    }


def require_generation_capacity(db: Session, user_id: int):
    """
    Return a 429 JSONResponse when the user hit a generation cap, else None.
    """
    from fastapi.responses import JSONResponse

    allowed, message = check_generation_cap(db, user_id)
    if allowed:
        return None
    return JSONResponse(
        status_code=429,
        content=generation_cap_json_content(db, user_id, message or "Generation limit reached."),
    )


def generation_cap_json_content(db: Session, user_id: int, message: str) -> dict:
    daily_count = get_user_generation_count(db, user_id, "daily")
    monthly_count = get_user_generation_count(db, user_id, "monthly")
    daily_cap, monthly_cap = get_generation_caps()
    return {
        "detail": message,
        "daily_remaining": max(0, daily_cap - daily_count),
        "monthly_remaining": max(0, monthly_cap - monthly_count),
        "cap_hit": generation_cap_hit_period(db, user_id),
        **generation_usage_payload(db, user_id),
    }
